### PR TITLE
Fix deploy action

### PR DESCRIPTION
**Pull request by wugologist**

### CODE REVIEW

**Review by raws — APPROVED** [review]
Huh, TIL that in addition to secrets, there are non-secret GitHub Actions environment variables. Looks good to me!

**Comment by wugologist** [comment]
@raws I guess you didn't see my attempts at a branch deploy [here](https://github.com/go-pound/ralph/actions/workflows/deploy-lambda.yml), because it most certainly does not look good to me. I guess I'll try to fix it

**Comment by raws** [comment]
Oh, yikes, I missed that. I'm also confused about why the last build is marked as successful, because the deploy to lambda step has [the same error as the broken builds](https://github.com/go-pound/ralph/actions/runs/4289481545/jobs/7472560325#step:4:3580) 🤔

**Comment by wugologist** [comment]
I no longer have any memory of writing this PR

**Pull request closed without merging**
